SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS 
    INNER JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE(SALES_DATE) BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 1, 3
ORDER BY 1, 3 DESC;


# 2022년 1월의 도서 판매 데이터를 기준
# 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여
# 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 출력
# 저자 ID를 오름차순, 저자 ID가 같다면 카테고리 내림차순 정렬