SELECT P.PRODUCT_CODE, P.PRICE*SUM(OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P LEFT JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC, 1 ASC;


# 상품코드 별  GROUP BY PRODUCT_CODE
# 매출액(판매가*판매량) 합계 P.PRICE * SUM(OS.SALES_AMOUNT)
# 매출액 기준 내림차순 정렬, 상품코드 기준 오름차순 정렬

