SELECT B.WRITER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3;


# 완료된 중고거래 총 금액이 70만원 이상인 사람(회원id, 닉네임, 총거래금액)조회.
# 필요 컬럼 : 거래별 가격 PRICE, 거레상태 STATUS, 작성자ID WRITER_ID
# WRITER_ID = USER_ID