SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE(START_DATE) BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5 
    ) AND DATE(START_DATE) BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC;
# 해당 날짜로 먼저 필터링
# 차별로 총 대여횟수 구하려면 1. 차별로 그룹화, 2. COUNT 로 필터링
# 위 데이터를 기준으로 월별, 아이디별로 출력 -> 1, 그룹화, 2. COUNT로 조회
# 이때 합산결과가 0이면 제외로 필터링