SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) 
IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;
# 식품 분류별 가격이 가장 비싼 식품 -> GROUP BY, MAX
# 식품 분류가 ('과자', '국', '김치', '식용유') -> WHERE IN
# 식품 가격 기준 내림차순 정렬 -> ORDER BY 
# 필요한 컬럼 : CATEGORY, PRICE, PRODUCT_NAME